apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cws-kubernetes
  region: us-east-2
  version: "1.22"
vpc:
  id: "vpc-028ee94e76e106c5b"
  cidr: "10.238.0.0/16"
  subnets:
    public:
      us-east-2a:
          id: subnet-0930cfcff0dd489f3
          cidr: "10.238.0.0/18"
      us-east-2b:
          id: subnet-0756fc2f7c91e43b5
          cidr: "10.238.64.0/18"
    private:
      us-east-2a:
          id: subnet-0adb671c0f2e88589
          cidr: "10.238.128.0/18"
      us-east-2b:
          id: subnet-03090c24a135ef60c
          cidr: "10.238.192.0/18"
managedNodeGroups:
- name: cws-group-public
  amiFamily: Ubuntu2004
  instanceType: t3.xlarge
  desiredCapacity: 2
  spot: true
nodeGroups:
- name: cws-group-private
  amiFamily: Ubuntu2004
  instanceType: m4.2xlarge
  desiredCapacity: 2
#  spot: true
  privateNetworking: true  