apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cws-k-spot
  region: us-east-2
  version: "1.22"
vpc:
  id: "vpc-0b866e3eb427dd056"
  subnets:
    public:
      us-east-2a:
          id: subnet-0f9c7d6da0ddfe6dd
      us-east-2b:
          id: subnet-023432486b48215ac
      us-east-2c:
          id: subnet-0f23c7f3d79273530          
    private:
      us-east-2a:
          id: subnet-0fa6570b1ec4261d8
      us-east-2b:
          id: subnet-04598072ce5318c8c
      us-east-2c:
          id: subnet-05eed30ea3b433ce9           