apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: devops-catalog
  region: us-east-2
  version: "1.22"
managedNodeGroups:
- name: cws-onegroup
  amiFamily: Ubuntu2004
  instanceType: t3.small
  minSize: 3
  maxSize: 6
  iam:
    withAddonPolicies:
      albInbgress: true
vpc:
  id: vpc-0b866e3eb427dd056
iam:
  serviceRoleARN: AWSServiceRoleForAmazonEKS
