apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cws-spot
  region: us-east-2
  version: "1.22"
vpc:
  id: "vpc-092e268171e9ee226"
  subnets:
    private:
      us-east-2a:
          id: "subnet-02c0fb78f2f3a7100"
      us-east-2c:
          id: "subnet-051a552271e173fe3"
    public:
      us-east-2a:
          id: "subnet-0db3a6bbd139635fd"
      us-east-2c:
          id: "subnet-03eca0b937094b155"
managedNodeGroups:
- name: cws-group-public
  amiFamily: Ubuntu2004
  instanceType: t3.xlarge
  minSize: 2
  maxSize: 3
  spot: true
- name: cws-group-private
  amiFamily: Ubuntu2004
  instanceType: m4.2xlarge
  minSize: 2
  maxSize: 3
  spot: true
  privateNetworking: true  
