apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cws-spot
  region: us-east-2
  version: "1.22"
vpc:
  id: "vpc-0303304c41102509a"
managedNodeGroups:
- name: cws-group-public
  amiFamily: AmazonLinux2
  instanceType: t3.xlarge
  desiredCapacity: 2
  spot: true
nodeGroups:
- name: cws-group-private
  amiFamily: AmazonLinux2
  instanceType: m4.2xlarge
  desiredCapacity: 2
#  spot: true
  privateNetworking: true  
