apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: devops-catalog
  region: us-east-1
  version: "1.22"
managedNodeGroups:
- name: cws-onegroup
  amiFamily: Ubuntu2004
  instanceType: t3.small
  minSize: 3
  maxSize: 6
  spot: true
