apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: cws-spot
  region: us-east-2
  version: "1.22"
managedNodeGroups:
- name: cws-group-large
  amiFamily: Ubuntu2004
  instanceType: m4.2xlarge
  minSize: 2
  maxSize: 3
  spot: true

